[tool.ruff]
# ignore long lines
lint.ignore = ["E501", "N806", "N802", "N803"]
lint.select = ["E", "F", "I", "N"]

[tool.mypy]
ignore_missing_imports = true
follow_imports = "silent"

[tool.black]
line-length = 100
