#!/bin/bash

# Check if a number of files is provided as an argument, otherwise default to 1
NUM_FILES=${1:-1}

# Check if input is 1, 5, or 10
if [[ "$NUM_FILES" -eq 1 || "$NUM_FILES" -eq 5 || "$NUM_FILES" -eq 10 ]]; then
    echo "Valid NUM_FILES: $NUM_FILES"
else
    echo "Error: Invalid input. Please use one of existing values: 1, 5, or 10."
    exit 1
fi

# Define the remote data prefix and other paths
REMOTE_DATA_PREFIX='root://eospublic.cern.ch//eos/root-eos/AGC'
HISTOS_FILE="histograms.root"
REFERENCE_HISTOS="reference/histos_${NUM_FILES}_file_per_process.json"
FIT_REFERENCE="../../.github/workflows/validation/fitResuts_${NUM_FILES}_file_validation_reference.yml"
HISTOGRAMS_REFERENCE="../../.github/workflows/validation/histograms_${NUM_FILES}_file_validation_reference.yml"

# Function to check the status of the previous command and exit if failed
check_status() {
  if [ $? -ne 0 ]; then
    echo "Test failed: $1"
    exit 1
  fi
}

# Step 1: Run Analysis
echo "Running analysis with ${NUM_FILES} file(s)..."
python analysis.py --n-max-files-per-sample ${NUM_FILES} --remote-data-prefix="${REMOTE_DATA_PREFIX}" --validation 1
check_status "Analysis failed"

# Step 2: Run validation sequences
echo "Running validation sequences..."
python validate_histograms.py --histos "${HISTOS_FILE}" --reference "${REFERENCE_HISTOS}" > output_histograms.txt
check_status "Histogram validation failed"

python reference/fitResults/validate_fit_result.py > output_fit_results.txt
check_status "FitResults validation failed"

# Step 3: Compare fitResults output with expected
echo "Comparing fitResults with expected results..."
diff output_fit_results.txt "${FIT_REFERENCE}"
if [ $? -ne 0 ]; then
  echo "Test failed: fitResults validation output does not match expected result."
  exit 1
fi

# Step 4: Compare histograms validation output with expected
echo "Comparing histograms validation with expected results..."
diff output_histograms.txt "${HISTOGRAMS_REFERENCE}"
if [ $? -ne 0 ]; then
  echo "Test failed: Histograms validation output does not match expected result."
  exit 1
fi

echo "All tests passed successfully."

