name: Validate CMS Open Data ttbar analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-pyroot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up ROOT environment
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev cmake g++ gcc binutils libx11-dev libncurses5-dev libssl-dev libxpm-dev \
            libxft-dev libxml2-dev libz-dev libxext-dev python3-dev git libtbb-dev libgif-dev xrootd-client python3
          pip install numpy plotting distributed tqdm uproot
          wget  https://root.cern/download/root_v6.32.04.Linux-ubuntu22.04-x86_64-gcc11.4.tar.gz
          tar -xzvf root_v6.32.04.Linux-ubuntu22.04-x86_64-gcc11.4.tar.gz
          source root/bin/thisroot.sh
          echo "ROOT is set up"

      - name: Run Analysis
        run: |
          source root/bin/thisroot.sh
          cd analyses/cms-open-data-ttbar/
          python analysis.py --n-max-files-per-sample 1 --remote-data-prefix='root://eospublic.cern.ch//eos/root-eos/AGC' --validation 1

      - name: Run validation sequences
        run: |
          source root/bin/thisroot.sh
          cd analyses/cms-open-data-ttbar/
          python validate_histograms.py --histos histograms.root --reference reference/histos_1_file_per_process.json > output_histograms.txt
          python reference/fitResults/validate_fit_result.py  > output.txt

      - name: Compare fitResults output with expected
        run: |
          diff analyses/cms-open-data-ttbar/output.txt .github/workflows/validation/fitResuts_1_file_validation_reference.yml

      - name: FitResults validation
        if: failure() # This step will be executed if the diff command finds differences
        run: |
          echo "Test failed: fitResults validation output does not match expected result."
      
      - name: Compare histograms validation output with expected
        run: |
          diff analyses/cms-open-data-ttbar/output_histograms.txt .github/workflows/validation/histograms_1_file_validation_reference.yml
          
      - name: Histograms validationw
        if: failure() # This step will be executed if the diff command finds differences
        run: |
          echo "Test failed: Histograms validation output does not match expected result."
